BASE = ../../
INCLUDE = -I $(BASE)/include
CFLAGS = -nostlib

TARGET = libSDL_gfx.a
SOURCES = SDL_framerate.c SDL_gfxBlitFunc.c SDL_gfxPrimitives.c SDL_imageFilter.c SDL_rotozoom.c

include $(BASE)/common.mk